package dev.omakey.core.emoji

/**
 * A small, curated word -> emoji lookup for the suggestion strip — typing "sad" offers 😢/😭/☹️
 * right next to the word suggestions, the same way most mainstream keyboards surface an emoji for
 * a word you're clearly already committed to. Deliberately just a static map, not a semantic/ML
 * lookup: exact, case-insensitive word match only, so it never guesses wrong on an unrelated word
 * that merely shares a prefix or root.
 */
object WordEmojiSuggestions {
    /** Up to [MAX_SUGGESTIONS] emoji for [word], or an empty list if it isn't in the table. Some
     * table entries list more than that (kept for future re-ranking use, e.g. a future skin-tone
     * or "most-used first" ordering) — capped here, at the single call site the suggestion strip
     * actually reads, so the row never grows past 2 chips regardless of how many an entry lists. */
    fun suggest(word: String): List<String> = table[word.lowercase()].orEmpty().take(MAX_SUGGESTIONS)

    private const val MAX_SUGGESTIONS = 2

    private val table: Map<String, List<String>> = buildMap {
        fun put(emoji: List<String>, vararg words: String) {
            words.forEach { this[it] = emoji }
        }

        put(listOf("😊", "😄", "🙂"), "happy", "glad")
        put(listOf("😢", "😭", "☹️"), "sad", "unhappy")
        put(listOf("😍", "❤️", "🥰"), "love", "loved")
        put(listOf("😡", "🤬", "😠"), "angry", "mad", "furious")
        put(listOf("😴", "🥱", "💤"), "tired", "sleepy", "exhausted")
        put(listOf("😋", "🍽️", "🤤"), "hungry", "starving")
        put(listOf("🥤", "💧"), "thirsty")
        put(listOf("🥶", "❄️"), "cold", "freezing")
        put(listOf("🥵", "🔥"), "hot")
        put(listOf("🤒", "🤢", "🤧"), "sick", "ill")
        put(listOf("🤩", "🎉", "😃"), "excited", "thrilled")
        put(listOf("😐", "🥱"), "bored")
        put(listOf("😱", "😨"), "scared", "afraid", "terrified")
        put(listOf("😲", "😮"), "surprised", "shocked")
        put(listOf("😕", "🤔"), "confused")
        put(listOf("😂", "🤣"), "lol", "haha", "hilarious", "funny")
        put(listOf("😭"), "crying")
        put(listOf("🥳", "🎉", "🎊"), "party", "celebrate", "celebration")
        put(listOf("🎂", "🎈", "🎁"), "birthday")
        put(listOf("🎉", "👏"), "congrats", "congratulations")
        put(listOf("🙏", "😊"), "thanks", "thankyou", "thank")
        put(listOf("😔", "🙏"), "sorry", "apologies")
        put(listOf("🙏"), "please")
        put(listOf("👍", "✅"), "yes", "yep", "sure")
        put(listOf("👎", "❌"), "no", "nope")
        put(listOf("👌", "✅"), "ok", "okay")
        put(listOf("😎", "👍"), "cool")
        put(listOf("🤩", "🔥"), "awesome", "amazing")
        put(listOf("👍", "💯"), "great", "good")
        put(listOf("👎", "😬"), "bad", "terrible", "awful")
        put(listOf("😮", "🤯"), "wow", "omg")
        put(listOf("🥰", "😍"), "cute", "adorable")
        put(listOf("😍", "✨"), "beautiful", "gorgeous", "pretty")
        put(listOf("🤢", "😖"), "ugly")
        put(listOf("🤪", "😜"), "crazy", "insane")
        put(listOf("☀️", "🌞"), "sun", "sunny")
        put(listOf("🌧️", "☔"), "rain", "rainy")
        put(listOf("❄️", "⛄"), "snow", "snowing")
        put(listOf("☕"), "coffee")
        put(listOf("🍵"), "tea")
        put(listOf("🍕"), "pizza")
        put(listOf("🎂", "🍰"), "cake")
        put(listOf("🍺"), "beer")
        put(listOf("🍷"), "wine")
        put(listOf("🐶", "🐕"), "dog", "puppy")
        put(listOf("🐱", "🐈"), "cat", "kitten")
        put(listOf("🎵", "🎶"), "music")
        put(listOf("🎬", "🍿"), "movie")
        put(listOf("🎮"), "game", "gaming")
        put(listOf("💼", "💻"), "work")
        put(listOf("😴", "🛏️"), "sleep")
        put(listOf("🏃"), "run", "running")
        put(listOf("🚶"), "walk", "walking")
        put(listOf("🍽️"), "eat", "eating")
        put(listOf("🏠", "🏡"), "home")
        put(listOf("🚗"), "car")
        put(listOf("📱"), "phone")
        put(listOf("💰", "💵"), "money")
        put(listOf("⏰", "⏱️"), "time")
        put(listOf("🔥"), "fire")
        put(listOf("💧", "🌊"), "water")
        put(listOf("⭐", "🌟"), "star")
        put(listOf("🌙"), "moon")
        put(listOf("❤️", "💕"), "heart")
        put(listOf("👍", "😊"), "fine")
        put(listOf("👋", "😊"), "welcome", "hello", "hi", "hey")
        put(listOf("👋", "😢"), "bye", "goodbye")
        put(listOf("💔"), "hate")
        put(listOf("🥺", "💭"), "miss")
        put(listOf("😌", "🙌"), "proud")
        put(listOf("😟", "😰"), "worried", "anxious")
        put(listOf("😬", "😰"), "nervous")
        put(listOf("😌", "🧘"), "relaxed", "calm")
        put(listOf("😩", "😫"), "stressed")
        put(listOf("🎓"), "graduation", "graduated")
        put(listOf("💪"), "strong", "workout", "gym")
        put(listOf("🙌", "🎉"), "yay")
        put(listOf("🤷"), "whatever", "idk")
        put(listOf("👀"), "look", "looking")
        put(listOf("💯"), "perfect")
        put(listOf("🥱"), "yawn", "yawning")
        put(listOf("🫡"), "salute", "saluting")

        // Family
        put(listOf("👨"), "man")
        put(listOf("👩"), "woman")
        put(listOf("👶"), "baby")
        put(listOf("👦"), "boy")
        put(listOf("👧"), "girl")
        put(listOf("👴"), "grandpa", "grandfather")
        put(listOf("👵"), "grandma", "grandmother")
        put(listOf("👪", "❤️"), "family")
        put(listOf("🤰"), "pregnant")
        put(listOf("💑", "❤️"), "couple")
        put(listOf("💍", "❤️"), "engaged", "engagement")
        put(listOf("👰"), "bride")
        put(listOf("🤵"), "groom")
        put(listOf("💒"), "wedding")

        // Animals
        put(listOf("🐭"), "mouse")
        put(listOf("🐹"), "hamster")
        put(listOf("🐰", "🐇"), "rabbit", "bunny")
        put(listOf("🦊"), "fox")
        put(listOf("🐻"), "bear")
        put(listOf("🐼"), "panda")
        put(listOf("🐨"), "koala")
        put(listOf("🦁"), "lion")
        put(listOf("🐯", "🐅"), "tiger")
        put(listOf("🐮", "🐄"), "cow")
        put(listOf("🐷", "🐖"), "pig")
        put(listOf("🐸"), "frog")
        put(listOf("🐵"), "monkey")
        put(listOf("🐔"), "chicken")
        put(listOf("🐧"), "penguin")
        put(listOf("🐦"), "bird")
        put(listOf("🦅"), "eagle")
        put(listOf("🦆"), "duck")
        put(listOf("🦉"), "owl")
        put(listOf("🐴", "🐎"), "horse")
        put(listOf("🦄"), "unicorn")
        put(listOf("🐝"), "bee")
        put(listOf("🐛"), "caterpillar")
        put(listOf("🦋"), "butterfly")
        put(listOf("🐌"), "snail")
        put(listOf("🐞"), "ladybug")
        put(listOf("🐜"), "ant")
        put(listOf("🕷️"), "spider")
        put(listOf("🐢"), "turtle")
        put(listOf("🐍"), "snake")
        put(listOf("🦎"), "lizard")
        put(listOf("🐙"), "octopus")
        put(listOf("🦀"), "crab")
        put(listOf("🐬"), "dolphin")
        put(listOf("🐳", "🐋"), "whale")
        put(listOf("🦈"), "shark")
        put(listOf("🐟"), "fish")
        put(listOf("🐘"), "elephant")
        put(listOf("🦒"), "giraffe")
        put(listOf("🦓"), "zebra")
        put(listOf("🐪", "🐫"), "camel")
        put(listOf("🦘"), "kangaroo")
        put(listOf("🐺"), "wolf")
        put(listOf("🦇"), "bat")
        put(listOf("🐿️"), "squirrel")
        put(listOf("🦔"), "hedgehog")

        // Food & drink
        put(listOf("🍔"), "burger", "hamburger")
        put(listOf("🍟"), "fries")
        put(listOf("🌭"), "hotdog")
        put(listOf("🌮"), "taco")
        put(listOf("🌯"), "burrito")
        put(listOf("🍣"), "sushi")
        put(listOf("🍜"), "ramen", "noodles")
        put(listOf("🍝"), "pasta", "spaghetti")
        put(listOf("🍞"), "bread")
        put(listOf("🥐"), "croissant")
        put(listOf("🥞"), "pancakes")
        put(listOf("🧇"), "waffle")
        put(listOf("🥓"), "bacon")
        put(listOf("🍳"), "egg", "eggs")
        put(listOf("🧀"), "cheese")
        put(listOf("🥗"), "salad")
        put(listOf("🍲"), "soup", "stew")
        put(listOf("🍚"), "rice")
        put(listOf("🍦"), "icecream")
        put(listOf("🍩"), "donut")
        put(listOf("🍪"), "cookie", "cookies")
        put(listOf("🍫"), "chocolate")
        put(listOf("🍬"), "candy")
        put(listOf("🍭"), "lollipop")
        put(listOf("🍎"), "apple")
        put(listOf("🍌"), "banana")
        put(listOf("🍊"), "orange")
        put(listOf("🍇"), "grapes")
        put(listOf("🍉"), "watermelon")
        put(listOf("🍓"), "strawberry")
        put(listOf("🍒"), "cherry", "cherries")
        put(listOf("🍑"), "peach")
        put(listOf("🍍"), "pineapple")
        put(listOf("🥑"), "avocado")
        put(listOf("🥕"), "carrot")
        put(listOf("🌽"), "corn")
        put(listOf("🥔"), "potato")
        put(listOf("🍄"), "mushroom")
        put(listOf("🥜"), "peanuts")
        put(listOf("🍯"), "honey")
        put(listOf("🥛"), "milk")
        put(listOf("🧃"), "juice")
        put(listOf("🥤"), "soda")
        put(listOf("🍻"), "cheers")
        put(listOf("🥂"), "toast")
        put(listOf("🍹"), "cocktail")
        put(listOf("🍾"), "champagne")

        // Nature & weather
        put(listOf("🌳", "🌲"), "tree")
        put(listOf("🌴"), "palmtree")
        put(listOf("🌵"), "cactus")
        put(listOf("🌸"), "blossom")
        put(listOf("🌹"), "rose")
        put(listOf("🌻"), "sunflower")
        put(listOf("🌷"), "tulip")
        put(listOf("🌼"), "flower", "flowers")
        put(listOf("🍁"), "autumn", "fall")
        put(listOf("🍂"), "leaves")
        put(listOf("🌱"), "sprout", "seedling")
        put(listOf("🌈"), "rainbow")
        put(listOf("⛈️"), "storm", "thunderstorm")
        put(listOf("⚡"), "lightning")
        put(listOf("🌪️"), "tornado")
        put(listOf("💨"), "wind", "windy")
        put(listOf("☁️"), "cloud", "cloudy")
        put(listOf("🌫️"), "fog", "foggy")
        put(listOf("🏔️"), "mountain")
        put(listOf("🌋"), "volcano")
        put(listOf("🏝️"), "island")
        put(listOf("🏜️"), "desert")
        put(listOf("🌊"), "ocean", "wave")
        put(listOf("🌍"), "world", "earth")

        // Sports & activities
        put(listOf("⚽"), "soccer")
        put(listOf("🏀"), "basketball")
        put(listOf("🏈"), "football")
        put(listOf("⚾"), "baseball")
        put(listOf("🎾"), "tennis")
        put(listOf("🏐"), "volleyball")
        put(listOf("🏉"), "rugby")
        put(listOf("🎱"), "billiards", "pool")
        put(listOf("🏓"), "pingpong")
        put(listOf("🏸"), "badminton")
        put(listOf("🥊"), "boxing")
        put(listOf("🥋"), "karate")
        put(listOf("⛳"), "golf")
        put(listOf("🎣"), "fishing")
        put(listOf("🏊"), "swimming", "swim")
        put(listOf("🚴"), "cycling", "biking")
        put(listOf("🏂"), "snowboarding")
        put(listOf("⛷️"), "skiing", "ski")
        put(listOf("🏋️"), "weightlifting")
        put(listOf("🤸"), "gymnastics")
        put(listOf("🧘"), "yoga", "meditation")
        put(listOf("🏆"), "trophy", "champion")
        put(listOf("🥇"), "gold", "firstplace")
        put(listOf("🥈"), "silver")
        put(listOf("🥉"), "bronze")
        put(listOf("🎯"), "target", "bullseye")
        put(listOf("🎳"), "bowling")
        put(listOf("🎨"), "art", "painting")
        put(listOf("📚"), "reading", "study", "studying")
        put(listOf("✍️"), "writing")
        put(listOf("💃"), "dance", "dancing")
        put(listOf("🎤"), "sing", "singing", "karaoke")
        put(listOf("🎧"), "podcast", "headphones")
        put(listOf("🎸"), "guitar")
        put(listOf("🎹"), "piano")
        put(listOf("🥁"), "drums")
        put(listOf("🎻"), "violin")
        put(listOf("🧩"), "puzzle")
        put(listOf("🎲"), "dice")

        // Travel & places
        put(listOf("✈️"), "plane", "flight", "flying")
        put(listOf("🚗"), "driving", "drive")
        put(listOf("🚕"), "taxi", "cab")
        put(listOf("🚌"), "bus")
        put(listOf("🚆", "🚄"), "train")
        put(listOf("🚲"), "bike", "bicycle")
        put(listOf("🏍️"), "motorcycle")
        put(listOf("🚀"), "rocket", "spacex")
        put(listOf("🛸"), "ufo", "aliens")
        put(listOf("⛵"), "sailing", "sailboat")
        put(listOf("🚢"), "ship", "cruise")
        put(listOf("⚓"), "anchor")
        put(listOf("🗺️"), "map")
        put(listOf("🧳"), "luggage", "packing")
        put(listOf("🛂"), "passport")
        put(listOf("🏨"), "hotel")
        put(listOf("🏖️"), "beach", "vacation")
        put(listOf("🏕️"), "camping")
        put(listOf("🗽"), "liberty")
        put(listOf("🗼"), "tower")
        put(listOf("🏰"), "castle")
        put(listOf("🏟️"), "stadium")
        put(listOf("🎡"), "ferriswheel")
        put(listOf("🎢"), "rollercoaster")
        put(listOf("🎠"), "carousel")

        // Objects & tech
        put(listOf("💻"), "laptop", "computer")
        put(listOf("🖥️"), "desktop")
        put(listOf("⌨️"), "keyboard")
        put(listOf("🖨️"), "printer")
        put(listOf("📷"), "camera", "photo")
        put(listOf("📺"), "tv", "television")
        put(listOf("📻"), "radio")
        put(listOf("⌚"), "watch")
        put(listOf("💡"), "idea", "lightbulb")
        put(listOf("🔦"), "flashlight")
        put(listOf("🔋"), "battery")
        put(listOf("🔌"), "charger", "plug")
        put(listOf("📖"), "book")
        put(listOf("📰"), "newspaper", "news")
        put(listOf("✏️"), "pencil")
        put(listOf("🖊️"), "pen")
        put(listOf("📎"), "paperclip")
        put(listOf("✂️"), "scissors")
        put(listOf("🔑"), "key")
        put(listOf("🔒"), "locked", "lock")
        put(listOf("🔓"), "unlocked", "unlock")
        put(listOf("🎁"), "gift", "present")
        put(listOf("👜"), "bag", "purse")
        put(listOf("🎒"), "backpack")
        put(listOf("👛"), "wallet")
        put(listOf("👓"), "glasses")
        put(listOf("🕶️"), "sunglasses")
        put(listOf("👑"), "crown", "king", "queen")
        put(listOf("💎"), "diamond")
        put(listOf("🔔"), "bell", "notification")
        put(listOf("📢"), "announcement")
        put(listOf("📌"), "pin", "pinned")
        put(listOf("🧵"), "thread")
        put(listOf("🧸"), "teddybear")
        put(listOf("☂️", "☔"), "umbrella")

        // Body
        put(listOf("👁️"), "eye")
        put(listOf("👀"), "eyes")
        put(listOf("👂"), "ear")
        put(listOf("👃"), "nose")
        put(listOf("👄"), "lips", "mouth")
        put(listOf("🦷"), "tooth", "teeth")
        put(listOf("🧠"), "brain")
        put(listOf("👅"), "tongue")
        put(listOf("🖐️", "✋"), "hand", "stop")
        put(listOf("👏"), "clap", "applause")
        put(listOf("🤝"), "handshake", "deal")
        put(listOf("✌️"), "peace")
        put(listOf("🤞"), "hopeful", "fingerscrossed")
        put(listOf("💪"), "muscle", "flex")
        put(listOf("🦶"), "foot")
        put(listOf("🦵"), "leg")

        // Professions
        put(listOf("👨‍⚕️", "👩‍⚕️"), "doctor", "nurse")
        put(listOf("👮"), "police", "cop")
        put(listOf("👨‍🚒", "👩‍🚒"), "firefighter")
        put(listOf("👨‍🏫", "👩‍🏫"), "teacher")
        put(listOf("👨‍🍳", "👩‍🍳"), "chef", "cook", "cooking")
        put(listOf("👨‍🌾", "👩‍🌾"), "farmer")
        put(listOf("👨‍🔬", "👩‍🔬"), "scientist")
        put(listOf("👨‍💻", "👩‍💻"), "programmer", "developer", "coding")
        put(listOf("👨‍🎨", "👩‍🎨"), "artist")
        put(listOf("👨‍✈️", "👩‍✈️"), "pilot")
        put(listOf("🕵️"), "detective", "spy")
        put(listOf("🦸"), "superhero", "hero")
        put(listOf("🧙"), "wizard")
        put(listOf("🎅"), "santa", "christmas")

        // Time & calendar
        put(listOf("🌅", "☀️"), "morning")
        put(listOf("🌆"), "evening")
        put(listOf("🌃", "🌙"), "night")
        put(listOf("📅"), "calendar", "schedule")
        put(listOf("⏳"), "waiting", "wait")
        put(listOf("⏲️"), "timer")
        put(listOf("🎊"), "confetti")
        put(listOf("🎃"), "halloween", "pumpkin")
        put(listOf("🦃"), "thanksgiving", "turkey")
        put(listOf("🐰", "🥚"), "easter")
        put(listOf("🎆"), "fireworks")
        put(listOf("🕯️"), "candle")

        // Misc reactions & symbols
        put(listOf("🔥", "💯"), "lit")
        put(listOf("💀"), "dead", "deadass")
        put(listOf("👻"), "ghost", "spooky")
        put(listOf("🤖"), "robot", "bot")
        put(listOf("👽"), "alien")
        put(listOf("🧟"), "zombie")
        put(listOf("🎭"), "drama", "theater")
        put(listOf("🚫"), "banned", "forbidden")
        put(listOf("⚠️"), "warning", "danger")
        put(listOf("❓"), "question")
        put(listOf("❗"), "important", "attention")
        put(listOf("✅"), "done", "complete", "completed")
        put(listOf("❌"), "wrong", "cancelled", "cancel")
        put(listOf("🆕"), "new")
        put(listOf("🆓"), "free")
        put(listOf("🔴"), "live")
        put(listOf("🚨"), "alert", "emergency")
        put(listOf("♻️"), "recycle", "recycling")
        put(listOf("🌐"), "internet", "global")
        put(listOf("📍"), "location")
        put(listOf("🧭"), "compass", "direction")
    }
}
